name: Reporte de error
description: Genera un reporte de error para ayudarnos a mejorar
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Bienvenido 游녦
        Gracias por ayudarme reportando este defecto
        por favor rellena los siguientes campos ya que esto har치 mas f치cil la reproducci칩n del defecto para poder solucionarlo
  - type: checkboxes
    attributes:
      label: Verificaciones preliminares
      description: Por favor aseg칰rese de verificar cada una de las casillas de verificaci칩n y de seguir las instrucciones de cada una de ellas.
      options:
        - label: "Este issue (o propuesta) no es un duplicado, antes de abrir un nuevo issue por favor verifique que no est칠 reportado ac치 https://github.com/Scot3004/secorto_web/issues"
          required: true
  - type: textarea
    attributes:
      label: Comportamiento esperado
      description: Describe el comportamiento que deber칤a tener el sitio web.
      placeholder: Se tan preciso como puedas y de ser posible adjunta una imagen de como deber칤a funcionar el sitio web.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comportamiento Actual
      description: Describe el comportamiento que deber칤a tener el sitio web.
      placeholder: Se tan preciso como puedas y de ser posible adjunta una imagen de lo que esta sucediendo, o bien la data de alg칰n dev tools.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Pasos para reproducir el error
      description: Definir paso a paso las acciones para reproducir el error.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
