name: Solicitud de mejora
description: Encontraste algo que crees que deber칤a tener el sitio web
labels: ["type: enhancement "]
body:
  - type: markdown
    attributes:
      value: |
        # Bienvenido 游녦
        Parece que consideras que mi sitio web tiene oportunidad de tener nuevas caracter칤sticas
  - type: checkboxes
    attributes:
      label: Verificaciones preliminares
      description: Por favor aseg칰rese de verificar cada una de las casillas de verificaci칩n y de seguir las instrucciones de cada una de ellas.
      options:
        - label: "Este issue (o propuesta) no es un duplicado, antes de abrir un nuevo issue por favor verifique que no est칠 reportado ac치 https://github.com/Scot3004/secorto_web/issues"
          required: true
  - type: textarea
    attributes:
      label: Solicitud de mejora en sitio web
      description: Especifica como se puede implementar la mejora que sugieres para el sitio web.
      placeholder: Se tan preciso como puedas y de ser posible adjunta una imagen de como deber칤a funcionar el sitio web.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ventajas
      description: Que ventajas supone lo que est치s sugiriendo a futuro.
      value: |
        1.
        2.
        3.
        ...
  - type: textarea
    attributes:
      label: Desventajas
      description: Cuales crees que podr칤an ser los inconvenientes que pueda ocasionar la implementaci칩n de lo que est치s sugiriendo a futuro.
      value: |
        1.
        2.
        3.
        ...
